<a href="https://colab.research.google.com/github/farrelakhdan/3A_07_FarrelMuhammad_MesinL_UTS/blob/main/Untitled1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
!pip install tweet-preprocessor
import preprocessor as p
import string 
import re
import nltk
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('stemmer')
from nltk.tokenize import word_tokenize 
from nltk.probability import FreqDist

from sklearn.metrics import confusion_matrix, accuracy_score, roc_auc_score, roc_curve
from sklearn.feature_extraction.text import CountVectorizer
from nltk.tokenize import RegexpTokenizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import SVC
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import LinearSVC

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report

import tensorflow as tf
from tensorflow import keras
from keras import models
from keras import layers
from tensorflow.keras import regularizers
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.layers import LSTM,GRU
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing.text import Tokenizer

import seaborn as sns
import matplotlib.pyplot as plt

from google.colab import files
import io

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting tweet-preprocessor
  Downloading tweet_preprocessor-0.6.0-py3-none-any.whl (27 kB)
Installing collected packages: tweet-preprocessor
Successfully installed tweet-preprocessor-0.6.0

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Error loading stemmer: Package 'stemmer' not found in
[nltk_data]     index

In [4]:
data = pd.read_csv('tweet_emotions.csv')
data.head()

     tweet_id   sentiment                                            content
0  1956967341       empty  @tiffanylue i know  i was listenin to bad habi...
1  1956967666     sadness  Layin n bed with a headache  ughhhh...waitin o...
2  1956967696     sadness                Funeral ceremony...gloomy friday...
3  1956967789  enthusiasm               wants to hang out with friends SOON!
4  1956968416     neutral  @dannycastillo We want to trade with someone w...

In [5]:
data['content'] = data['content'].replace(regex='(@\w+)|#|&|!',value='')
data.head()

     tweet_id   sentiment                                            content
0  1956967341       empty   i know  i was listenin to bad habit earlier a...
1  1956967666     sadness  Layin n bed with a headache  ughhhh...waitin o...
2  1956967696     sadness                Funeral ceremony...gloomy friday...
3  1956967789  enthusiasm                wants to hang out with friends SOON
4  1956968416     neutral   We want to trade with someone who has Houston...

In [6]:
data['content']=data.content.apply(lambda x : p.clean(x))
data.head()

     tweet_id   sentiment                                            content
0  1956967341       empty  i know i was listenin to bad habit earlier and...
1  1956967666     sadness  Layin n bed with a headache ughhhh...waitin on...
2  1956967696     sadness                Funeral ceremony...gloomy friday...
3  1956967789  enthusiasm                wants to hang out with friends SOON
4  1956968416     neutral  We want to trade with someone who has Houston ...

In [7]:
data["content"][1:10]

1    Layin n bed with a headache ughhhh...waitin on...
2                  Funeral ceremony...gloomy friday...
3                  wants to hang out with friends SOON
4    We want to trade with someone who has Houston ...
5    Re-pinging : why didn't you go to prom? BC my ...
6    I should be sleep, but im not thinking about a...
7                                        Hmmm. is down
8                         Charlene my love. I miss you
9                      I'm sorry at least it's Friday?
Name: content, dtype: object

In [8]:
def remove_tweet_special(text):

    text = text.replace('\\t'," ").replace('\\n'," ").replace('\\u'," ").replace('\\',"")
    
    text = text.encode('ascii', 'replace').decode('ascii')
    
    text = ' '.join(re.sub("([@#][A-Za-z0-9]+)|(\w+:\/\/\S+)"," ", text).split())
    
    return text.replace("http://", " ").replace("https://", " ")
                
data['content'] = data['content'].apply(remove_tweet_special)


def remove_number(text):
    return  re.sub(r"\d+", "", text)

data['content'] = data['content'].apply(remove_number)


def remove_punctuation(text):
    return text.translate(str.maketrans("","",string.punctuation))

data['content'] = data['content'].apply(remove_punctuation)


def remove_whitespace_LT(text):
    return text.strip()

data['content'] = data['content'].apply(remove_whitespace_LT)


def remove_whitespace_multiple(text):
    return re.sub('\s+',' ',text)

data['content'] = data['content'].apply(remove_whitespace_multiple)

def remove_singl_char(text):
    return re.sub(r"\b[a-zA-Z]\b", "", text)

data['content'] = data['content'].apply(remove_singl_char)

print(data['content'].head())
print('\n\n\n')

0     know  was listenin to bad habit earlier and  ...
1    Layin  bed with  headache ughhhhwaitin on your...
2                        Funeral ceremonygloomy friday
3                  wants to hang out with friends SOON
4    We want to trade with someone who has Houston ...
Name: content, dtype: object

In [9]:
data.head(50)

      tweet_id   sentiment                                            content
0   1956967341       empty   know  was listenin to bad habit earlier and  ...
1   1956967666     sadness  Layin  bed with  headache ughhhhwaitin on your...
2   1956967696     sadness                      Funeral ceremonygloomy friday
3   1956967789  enthusiasm                wants to hang out with friends SOON
4   1956968416     neutral  We want to trade with someone who has Houston ...
5   1956968477       worry  Repinging why didnt you go to prom BC my bf di...
6   1956968487     sadness   should be sleep but im not thinking about an ...
7   1956968636       worry                                       Hmmm is down
8   1956969035     sadness                         Charlene my love  miss you
9   1956969172     sadness                       Im sorry at least its Friday
10  1956969456     neutral                                   cant fall asleep
11  1956969531       worry                            Choked on her retainers
12  1956970047     sadness  Ugh  have to beat this stupid song to get to t...
13  1956970424     sadness  if  watch the hills in london  will realise wh...
14  1956970860    surprise                                       Got the news
15  1956971077     sadness      The storm is here and the electricity is gone
16  1956971170        love                                             agreed
17  1956971206     sadness  So sleepy again and its not even that late  fa...
18  1956971473       worry  lady gaga tweeted about not being impressed by...
19  1956971586     sadness  How are YOU convinced that  have always wanted...
20  1956971981       worry  oh too bad  hope it gets better Ive been havin...
21  1956972097         fun  Wondering why Im awake at amwriting  new songp...
22  1956972116     neutral  No Topic Maps talks at the Balisage Markup Con...
23  1956972270       worry   ate Something  dont know what it is Why do  k...
24  1956972359     sadness  so tired and  think im definitely going to get...
25  1956972444       worry  On my way home  having deal  underage girls dr...
26  1956972557     sadness  im sorry people are so rude to you isaac they ...
27  1956972884       worry  Damm servers still down  need to hit before al...
28  1956973598     sadness  Fudge Just BSd that whole paper So tired Ugh  ...
29  1956973690       worry             HATE CANCER  HATE IT  HATE IT  HATE IT
30  1956974706        hate  It is so annoying when she starts typing on he...
31  1956975441     neutral                                         cant sleep
32  1956975860     neutral                                 missed the bly bus
33  1956975876     neutral      feels strong contractions but wants to go out
34  1956975927     neutral                 SoCal stoked or maybe not tomorrow
35  1956976187     neutral                         Screw you  only have weeks
36  1956976312     sadness  yeah  feel all funny cause  havent slept enoug...
37  1956976371       worry                               need skott right now
38  1956976557     neutral                            has work this afternoon
39  1956976681     neutral  Aw you would not unfollow me would you Then  w...
40  1956977084   happiness  mmm much better day so far its still quite ear...
41  1956977187         fun  lt your gonna be the first twitter cause your ...
42  1956977618       worry  just picked up her Blackberry from the middle ...
43  1956977624       worry  Why do  have the feeling  should be packing an...
44  1956978276       empty  middle school and elem High schools will remai...
45  1956978410       worry  Bed its time hope  go to school tomorrow all t...
46  1956978668       worry  Ahh Well  was hoping that  could learn some st...
47  1956979150     sadness  Im having  problem with my photo here in twitt...
48  1956979437     neutral  oh noooo if  blow  tire youre reaaaally going ...
49  1956979756     neutral                                    wnna take  bath

In [ ]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

stop_words = stopwords.words('english')
data['content'] = data['content'].apply(lambda x: ' '.join([word for word in x.split() if word not in (stop_words)]))
data['content'] = data['content'].apply(lambda x: ' '.join([item for item in x.split() if item not in (stop_words)]))
print(data.head())

     tweet_id   sentiment                                            content
0  1956967341       empty  know listenin bad habit earlier started freaki...
1  1956967666     sadness               Layin bed headache ughhhhwaitin call
2  1956967696     sadness                      Funeral ceremonygloomy friday
3  1956967789  enthusiasm                            wants hang friends SOON
4  1956968416     neutral          We want trade someone Houston tickets one

In [ ]:
print(data['sentiment'].value_counts())
print('\n')

neutral       8638
worry         8459
happiness     5209
sadness       5165
love          3842
surprise      2187
fun           1776
relief        1526
hate          1323
empty          827
enthusiasm     759
boredom        179
anger          110
Name: sentiment, dtype: int64

In [ ]:
# Data untuk label
new_labels = {
    'neutral': 0,
    'worry': 1,
    'happiness': 2,
    'sadness': 3,
    'love': 4,
    'surprise': 5,
    'fun': 6,
    'relief': 7,
    'hate': 8,
    'empty': 9,
    'enthusiasm': 10,
    'boredom': 11,
    'anger' : 12
}

# Encode label
data['sentiment'] = data['sentiment'].map(new_labels)

# Cek data
data.head()

     tweet_id  sentiment                                            content
0  1956967341          9  know listenin bad habit earlier started freaki...
1  1956967666          3               Layin bed headache ughhhhwaitin call
2  1956967696          3                      Funeral ceremonygloomy friday
3  1956967789         10                            wants hang friends SOON
4  1956968416          0          We want trade someone Houston tickets one

In [ ]:
X = data['content'].values
y = data['sentiment'].values

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=50)
bow = CountVectorizer()
X_train = bow.fit_transform(X_train)
X_test = bow.transform(X_test)

In [ ]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

# Inisiasi MultinomialNB
mnb = MultinomialNB()

# Fit model
mnb.fit(X_train, y_train)

# Prediksi dengan data training
y_pred_train = mnb.predict(X_train)

# Evaluasi akurasi data training
acc_train = accuracy_score(y_train, y_pred_train)

# Prediksi dengan data training
y_pred_test = mnb.predict(X_test)

# Evaluasi akurasi data training
acc_test = accuracy_score(y_test, y_pred_test)

# Print hasil evaluasi
print(f'Hasil akurasi data train: {acc_train}')
print(f'Hasil akurasi data test: {acc_test}')

Hasil akurasi data train: 0.55671875
Hasil akurasi data test: 0.325625

By
Aryo Bagus Kusuma D T / 03
Farrel Muhammad R A / 07
Maulana Syarief H / 14
Primo Afga Parlevi / 20
Rafli Alfian N / 23
Rijal Ammar I I / 28